# Generated by Django 6.0.5 on 2026-05-26 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="has_delete",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="has_read",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="has_update",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="has_write",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-created_at"],
            },
        ),
    ]
