# Generated by Django 6.0.5 on 2026-05-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0002_resource_has_delete_resource_has_read_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
    ]
